/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.polypro.duan1quanlynongsan.GiaoDien;

//import com.polypro.duan1quanlynongsan.Dao.ThongKeDao;
import com.polypro.duan1quanlynongsan.Helper.JdialogHelper;
import com.polypro.duan1quanlynongsan.Helper.ShareHelper;
import com.polypro.duan1quanlynongsan.Model.KhachHang;
import com.polypro.duan1quanlynongsan.Model.NhanVien;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;



/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
     int index;
    public Main() {
        
        initComponents();
        init();
          
      
    }

//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        bntNongSan = new javax.swing.JButton();
        btnGiamGia = new javax.swing.JButton();
        btnHuongDan = new javax.swing.JButton();
        btnGioiThieu = new javax.swing.JButton();
        btnGioiTinh = new javax.swing.JButton();
        btnNhap = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHeThong = new javax.swing.JMenu();
        jMenuItemDangXuat = new javax.swing.JMenuItem();
        jMenuItemDangNhap = new javax.swing.JMenuItem();
        jMenuItemDoiMK = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemKetThuc = new javax.swing.JMenuItem();
        jMenuQuanLy = new javax.swing.JMenu();
        jMenuItemQLNhanVien = new javax.swing.JMenuItem();
        jMenuItemNhaCungCap = new javax.swing.JMenuItem();
        jMenuItemQLNongSan = new javax.swing.JMenuItem();
        QLKhachHang = new javax.swing.JMenuItem();
        jMenuTongHop = new javax.swing.JMenu();
        jMenuItemPhieuNhap = new javax.swing.JMenuItem();
        jMenuItemPhieuXuat = new javax.swing.JMenuItem();
        jMenuItemDOanhThu = new javax.swing.JMenuItem();
        jMenuUuDai = new javax.swing.JMenu();
        jMenuItemGiamGia = new javax.swing.JMenuItem();
        jMenuItemKhachHang = new javax.swing.JMenuItem();
        jMenuTroGiup = new javax.swing.JMenu();
        jMenuItemGioiThieu = new javax.swing.JMenuItem();
        jMenuItemHuongDan = new javax.swing.JMenuItem();
        jMenuNgonNgu = new javax.swing.JMenu();
        Tienganh = new javax.swing.JCheckBoxMenuItem();
        TiengViet = new javax.swing.JCheckBoxMenuItem();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao Diện");

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Log out.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setDefaultCapable(false);
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Boy.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setDefaultCapable(false);
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        bntNongSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Brightness.png"))); // NOI18N
        bntNongSan.setText("Nông Sản");
        bntNongSan.setDefaultCapable(false);
        bntNongSan.setFocusable(false);
        bntNongSan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntNongSan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntNongSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNongSanActionPerformed(evt);
            }
        });

        btnGiamGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Certificate.png"))); // NOI18N
        btnGiamGia.setText("Giảm Gía");
        btnGiamGia.setDefaultCapable(false);
        btnGiamGia.setFocusable(false);
        btnGiamGia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGiamGia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamGiaActionPerformed(evt);
            }
        });

        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Globe.png"))); // NOI18N
        btnHuongDan.setText("Hướng Dẫn");
        btnHuongDan.setDefaultCapable(false);
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });

        btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Home.png"))); // NOI18N
        btnGioiThieu.setText("Giới Thiệu");
        btnGioiThieu.setDefaultCapable(false);
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });

        btnGioiTinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Calculator.png"))); // NOI18N
        btnGioiTinh.setText("Máy Tính");
        btnGioiTinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiTinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiTinhActionPerformed(evt);
            }
        });

        btnNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Add to basket.png"))); // NOI18N
        btnNhap.setText("Đơn Nhập");
        btnNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntNongSan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnGioiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntNongSan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuongDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/3-BI-KIP-dam-bao-chat-luong-nong-san.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2037, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblDongHo.setBackground(new java.awt.Color(255, 255, 255));
        lblDongHo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(0, 0, 255));
        lblDongHo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Clock.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/eng.gif"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/vit.gif"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jMenuHeThong.setText("Hệ Thống");

        jMenuItemDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Log out.png"))); // NOI18N
        jMenuItemDangXuat.setText("Đăng Xuất");
        jMenuItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDangXuatActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemDangXuat);

        jMenuItemDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Login.png"))); // NOI18N
        jMenuItemDangNhap.setText("Đăng nhập");
        jMenuItemDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDangNhapActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemDangNhap);

        jMenuItemDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Refresh.png"))); // NOI18N
        jMenuItemDoiMK.setText("Đổi Mật Khẩu");
        jMenuItemDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDoiMKActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemDoiMK);
        jMenuHeThong.add(jSeparator1);

        jMenuItemKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Stop.png"))); // NOI18N
        jMenuItemKetThuc.setText("Kết thúc");
        jMenuItemKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKetThucActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemKetThuc);

        jMenuBar1.add(jMenuHeThong);

        jMenuQuanLy.setText("Quản Lý");

        jMenuItemQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/User group.png"))); // NOI18N
        jMenuItemQLNhanVien.setText("Quản Lý Nhân Viên");
        jMenuItemQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQLNhanVienActionPerformed(evt);
            }
        });
        jMenuQuanLy.add(jMenuItemQLNhanVien);

        jMenuItemNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Clien list.png"))); // NOI18N
        jMenuItemNhaCungCap.setText("Nhà Cung Cấp");
        jMenuItemNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNhaCungCapActionPerformed(evt);
            }
        });
        jMenuQuanLy.add(jMenuItemNhaCungCap);

        jMenuItemQLNongSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Color wheel.png"))); // NOI18N
        jMenuItemQLNongSan.setText("Quản Lý Nông Sản");
        jMenuItemQLNongSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQLNongSanActionPerformed(evt);
            }
        });
        jMenuQuanLy.add(jMenuItemQLNongSan);

        QLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Friends.png"))); // NOI18N
        QLKhachHang.setText("Quản Lý Khách Hàng");
        QLKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLKhachHangActionPerformed(evt);
            }
        });
        jMenuQuanLy.add(QLKhachHang);

        jMenuBar1.add(jMenuQuanLy);

        jMenuTongHop.setText("Tổng Hợp");

        jMenuItemPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Add to basket.png"))); // NOI18N
        jMenuItemPhieuNhap.setText("Phiếu Nhập");
        jMenuItemPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPhieuNhapActionPerformed(evt);
            }
        });
        jMenuTongHop.add(jMenuItemPhieuNhap);

        jMenuItemPhieuXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Left.png"))); // NOI18N
        jMenuItemPhieuXuat.setText("Phiếu Xuất");
        jMenuItemPhieuXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPhieuXuatActionPerformed(evt);
            }
        });
        jMenuTongHop.add(jMenuItemPhieuXuat);

        jMenuItemDOanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Diagram.png"))); // NOI18N
        jMenuItemDOanhThu.setText("Quản Lý Doanh Thu");
        jMenuItemDOanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDOanhThuActionPerformed(evt);
            }
        });
        jMenuTongHop.add(jMenuItemDOanhThu);

        jMenuBar1.add(jMenuTongHop);

        jMenuUuDai.setText("Ưu đãi");

        jMenuItemGiamGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Certificate.png"))); // NOI18N
        jMenuItemGiamGia.setText("Sản Phẩm Giảm Giá");
        jMenuItemGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGiamGiaActionPerformed(evt);
            }
        });
        jMenuUuDai.add(jMenuItemGiamGia);

        jMenuItemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Gift.png"))); // NOI18N
        jMenuItemKhachHang.setText("Qùa Tặng Khách Hàng");
        jMenuItemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKhachHangActionPerformed(evt);
            }
        });
        jMenuUuDai.add(jMenuItemKhachHang);

        jMenuBar1.add(jMenuUuDai);

        jMenuTroGiup.setText("Trợ Giúp");

        jMenuItemGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Heart.png"))); // NOI18N
        jMenuItemGioiThieu.setText("Giới Thiệu");
        jMenuItemGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGioiThieuActionPerformed(evt);
            }
        });
        jMenuTroGiup.add(jMenuItemGioiThieu);

        jMenuItemHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Globe.png"))); // NOI18N
        jMenuItemHuongDan.setText("Hướng Dẫn");
        jMenuItemHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHuongDanActionPerformed(evt);
            }
        });
        jMenuTroGiup.add(jMenuItemHuongDan);

        jMenuNgonNgu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polypro/duan1quanlynongsan/hinh/Edit.png"))); // NOI18N
        jMenuNgonNgu.setText("Cài Đặt Ngôn Ngữ");

        Tienganh.setSelected(true);
        Tienganh.setText("Tiếng anh");
        Tienganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TienganhActionPerformed(evt);
            }
        });
        jMenuNgonNgu.add(Tienganh);

        TiengViet.setSelected(true);
        TiengViet.setText("Tiếng Việt");
        TiengViet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiengVietActionPerformed(evt);
            }
        });
        jMenuNgonNgu.add(TiengViet);

        jMenuTroGiup.add(jMenuNgonNgu);

        jMenuBar1.add(jMenuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDangNhapActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDangNhapActionPerformed

    private void jMenuItemQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQLNhanVienActionPerformed
       NhanVien nv = ShareHelper.nv;
        if (nv.getVaiTro() == 0) {
            JdialogHelper.showmessager(this, "chỉ có chủ mới có thể xem thông tin này \n", "thông báo");
            return;
        }
        NhanVienJFrame NhanVien = new NhanVienJFrame();
        NhanVien.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItemQLNhanVienActionPerformed

    private void jMenuItemDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDoiMKActionPerformed
       CuaSoDoiMatKhau dmk = new CuaSoDoiMatKhau();
        dmk.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDoiMKActionPerformed

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
     CuaSoGioiThieu GioiThieu = new CuaSoGioiThieu(this, true);
        GioiThieu.setVisible(true);
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void jMenuItemGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGioiThieuActionPerformed
        CuaSoGioiThieu GioiThieu = new CuaSoGioiThieu(this, true);
        GioiThieu.setVisible(true);
    }//GEN-LAST:event_jMenuItemGioiThieuActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
ChaoJ chao = new ChaoJ(this, rootPaneCheckingEnabled);
        Login dangNhap = new Login(this, true);
        dangNhap.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void jMenuItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDangXuatActionPerformed
ChaoJ chao = new ChaoJ(this, rootPaneCheckingEnabled);
        Login dangNhap = new Login(this, true);
        dangNhap.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDangXuatActionPerformed

    private void jMenuItemKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKetThucActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemKetThucActionPerformed

    private void btnGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiTinhActionPerformed

       Caculator mt = new Caculator();
       mt.setVisible(true); 
       // TODO add your handling code here:
    }//GEN-LAST:event_btnGioiTinhActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
 NhanVien nv = ShareHelper.nv;
        if (nv.getVaiTro() == 0) {
            JdialogHelper.showmessager(this, "chỉ có chủ mới có thể xem thông tin này \n", "thông báo");
            return;
        }
        NhanVienJFrame NhanVien = new NhanVienJFrame();
        NhanVien.setVisible(true);
        
                // TODO add your handling code here:
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void jMenuItemDOanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDOanhThuActionPerformed
       NhanVien nv = ShareHelper.nv;
        if (nv.getVaiTro() == 0) {
            JdialogHelper.showmessager(this, "chỉ có chủ mới có thể xem thông tin này \n", "thông báo");
            return;
        }
        DoanhThu a = new DoanhThu();
        a.setVisible(true);
         
        a.edit(0);
    }//GEN-LAST:event_jMenuItemDOanhThuActionPerformed

    private void QLKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLKhachHangActionPerformed
         QLKhachHang a = new QLKhachHang();
        a.setVisible(true);
    }//GEN-LAST:event_QLKhachHangActionPerformed

    private void jMenuItemNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNhaCungCapActionPerformed
  
  
        GDNhaCungCap NCC = new GDNhaCungCap();
        NCC.setVisible(true);
   
    }//GEN-LAST:event_jMenuItemNhaCungCapActionPerformed

    private void jMenuItemQLNongSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQLNongSanActionPerformed
        QLNongSan ns = new QLNongSan();
        ns.setVisible(true);
    }//GEN-LAST:event_jMenuItemQLNongSanActionPerformed

    private void jMenuItemPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPhieuNhapActionPerformed
        GDnhapHang ns = new GDnhapHang();
        ns.setVisible(true);
    }//GEN-LAST:event_jMenuItemPhieuNhapActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
     GDnhapHang ns = new GDnhapHang();
        ns.setVisible(true);
    }//GEN-LAST:event_btnNhapActionPerformed

    private void jMenuItemPhieuXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPhieuXuatActionPerformed
         GDPhieuXuat ns = new GDPhieuXuat();
        ns.setVisible(true);
    }//GEN-LAST:event_jMenuItemPhieuXuatActionPerformed

    private void TienganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TienganhActionPerformed
        jMenuHeThong.setText("System");
        jMenuQuanLy.setText("manage");
        jMenuTongHop.setText("synthetic");
        jMenuUuDai.setText("endow");
        jMenuTroGiup.setText("Help");
        jMenuItemDangNhap.setText("Log in");
        jMenuItemDangXuat.setText("Log Out");
        jMenuItemDoiMK.setText("Change Password");
        jMenuItemKetThuc.setText("exits");
        jMenuItemQLNhanVien.setText("Staff");
        jMenuItemQLNongSan.setText("Agricultural");
        jMenuItemKhachHang.setText("customer");
        jMenuItemNhaCungCap.setText("supplier");
        jMenuItemPhieuNhap.setText("Enter coupon");
        jMenuItemPhieuXuat.setText("Bill");
        jMenuItemDOanhThu.setText("revenue");
        jMenuItemGiamGia.setText("Discount ");
        jMenuItemKhachHang.setText("Gift to Customers");
        jMenuNgonNgu.setText("language");
        jMenuItemHuongDan.setText("Tutorial");
         QLKhachHang.setText("Customer");
        Tienganh.setText("English");
         TiengViet.setText("Vietnamese");
       jMenuItemGioiThieu.setText("Introduce");
         
         btnDangXuat.setText("Log in");
          btnNhanVien.setText("Staff");
           btnGiamGia.setText("Discount");
            btnHuongDan.setText("Tutorial");
             btnNhap.setText("Enter coupon");
              btnGioiThieu.setText("Introduce");
               btnGioiTinh.setText("cacularto");
           
       
              // TODO add your handling code here:
    }//GEN-LAST:event_TienganhActionPerformed

    private void TiengVietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiengVietActionPerformed
jMenuHeThong.setText("Hệ Thống");
        jMenuQuanLy.setText("Quản Lý");
        jMenuTongHop.setText("Tổng Hợp");
        jMenuUuDai.setText("Ưu Đãi");
        jMenuTroGiup.setText("Trợ Giúp");  
        jMenuItemDangNhap.setText("Đăng Nhập");
        jMenuItemDangXuat.setText("Đăng Xuất");
        jMenuItemDoiMK.setText("Đổi Mật Khẩu");
        jMenuItemKetThuc.setText("Kết Thúc");
        jMenuItemQLNhanVien.setText("Nhân Viên");
        jMenuItemQLNongSan.setText("Nông Sản");
        jMenuItemKhachHang.setText("Khách Hàng");
        jMenuItemNhaCungCap.setText("Nhà Cung Cấp");
        jMenuItemPhieuNhap.setText("Phiếu Nhập");
        jMenuItemPhieuXuat.setText("Phiếu Xuất");
        jMenuItemDOanhThu.setText("Doanh Thu");
        jMenuItemGiamGia.setText("Giảm Gía ");
        jMenuItemKhachHang.setText("Qùa Tặng Khách Hàng");
        jMenuNgonNgu.setText("Ngôn Ngữ");
        jMenuItemHuongDan.setText("Hướng Dẫn");
       QLKhachHang.setText("Khách Hàng");
        Tienganh.setText("Tiếng Anh");
         TiengViet.setText("Tiếng Việt");
 btnDangXuat.setText("Đăng Nhập");
          btnNhanVien.setText("Nhân Viên");
           btnGiamGia.setText("Giảm Gía");
            btnHuongDan.setText("Hướng Dẫn");
             btnNhap.setText("Đơn nhập");
              btnGioiThieu.setText("Giới Thiệu");
               btnGioiTinh.setText("Máy Tính");

jMenuItemGioiThieu.setText("Giới Thiệu");// TODO add your handling code here:
    }//GEN-LAST:event_TiengVietActionPerformed

    private void jMenuItemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKhachHangActionPerformed
 DoanhThu a = new DoanhThu();
        a.setVisible(true);
         
        a.edit(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemKhachHangActionPerformed

    private void bntNongSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNongSanActionPerformed
  QLNongSan ns = new QLNongSan();
        ns.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bntNongSanActionPerformed

    private void jMenuItemGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGiamGiaActionPerformed
       DoanhThu a = new DoanhThu();
        a.setVisible(true);
         
        a.edit(2);    
    }//GEN-LAST:event_jMenuItemGiamGiaActionPerformed

    private void btnGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamGiaActionPerformed
DoanhThu a = new DoanhThu();
        a.setVisible(true);
         
        a.edit(2);            // TODO add your handling code here:
    }//GEN-LAST:event_btnGiamGiaActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        
        jMenuItemGioiThieu.setText("Giới Thiệu");
        jMenuHeThong.setText("Hệ Thống");
        jMenuQuanLy.setText("Quản Lý");
        jMenuTongHop.setText("Tổng Hợp");
        jMenuUuDai.setText("Ưu Đãi");
        jMenuTroGiup.setText("Trợ Giúp");  
        jMenuItemDangNhap.setText("Đăng Nhập");
        jMenuItemDangXuat.setText("Đăng Xuất");
        jMenuItemDoiMK.setText("Đổi Mật Khẩu");
        jMenuItemKetThuc.setText("Kết Thúc");
        jMenuItemQLNhanVien.setText("Nhân Viên");
        jMenuItemQLNongSan.setText("Nông Sản");
        jMenuItemKhachHang.setText("Khách Hàng");
        jMenuItemNhaCungCap.setText("Nhà Cung Cấp");
        jMenuItemPhieuNhap.setText("Phiếu Nhập");
        jMenuItemPhieuXuat.setText("Phiếu Xuất");
        jMenuItemDOanhThu.setText("Doanh Thu");
        jMenuItemGiamGia.setText("Giảm Gía ");
        jMenuItemKhachHang.setText("Qùa Tặng Khách Hàng");
        jMenuNgonNgu.setText("Ngôn Ngữ");
        jMenuItemHuongDan.setText("Hướng Dẫn");
       QLKhachHang.setText("Khách Hàng");
        Tienganh.setText("Tiếng Anh");
         TiengViet.setText("Tiếng Việt");
 btnDangXuat.setText("Đăng Nhập");
          btnNhanVien.setText("Nhân Viên");
           btnGiamGia.setText("Giảm Gía");
            btnHuongDan.setText("Hướng Dẫn");
             btnNhap.setText("Đơn nhập");
              btnGioiThieu.setText("Giới Thiệu");
               btnGioiTinh.setText("Máy Tính");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
  jMenuHeThong.setText("System");
        jMenuQuanLy.setText("manage");
        jMenuTongHop.setText("synthetic");
        jMenuUuDai.setText("endow");
        jMenuTroGiup.setText("Help");
        jMenuItemDangNhap.setText("Log in");
        jMenuItemDangXuat.setText("Log Out");
        jMenuItemDoiMK.setText("Change Password");
        jMenuItemKetThuc.setText("exits");
        jMenuItemQLNhanVien.setText("Staff");
        jMenuItemQLNongSan.setText("Agricultural");
        jMenuItemKhachHang.setText("customer");
        jMenuItemNhaCungCap.setText("supplier");
        jMenuItemPhieuNhap.setText("Enter coupon");
        jMenuItemPhieuXuat.setText("Bill");
        jMenuItemDOanhThu.setText("revenue");
        jMenuItemGiamGia.setText("Discount ");
        jMenuItemKhachHang.setText("Gift to Customers");
        jMenuNgonNgu.setText("language");
        jMenuItemHuongDan.setText("Tutorial");
         QLKhachHang.setText("Customer");
        Tienganh.setText("English");
         TiengViet.setText("Vietnamese");
       jMenuItemGioiThieu.setText("Introduce");
         
         btnDangXuat.setText("Log in");
          btnNhanVien.setText("Staff");
           btnGiamGia.setText("Discount");
            btnHuongDan.setText("Tutorial");
             btnNhap.setText("Enter coupon");
              btnGioiThieu.setText("Introduce");
               btnGioiTinh.setText("cacularto");      
              
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
try {
            Desktop.getDesktop().browse(new File("C:\\Users\\Admin\\Desktop\\DUAN1\\index.html").toURI());
        } catch (Exception e) {
            System.out.println(e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void jMenuItemHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHuongDanActionPerformed
try {
            Desktop.getDesktop().browse(new File("C:\\Users\\Admin\\Desktop\\DUAN1\\index.html").toURI());
        } catch (Exception e) {
            System.out.println(e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemHuongDanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem QLKhachHang;
    private javax.swing.JCheckBoxMenuItem TiengViet;
    private javax.swing.JCheckBoxMenuItem Tienganh;
    private javax.swing.JButton bntNongSan;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnGiamGia;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnGioiTinh;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHeThong;
    private javax.swing.JMenuItem jMenuItemDOanhThu;
    private javax.swing.JMenuItem jMenuItemDangNhap;
    private javax.swing.JMenuItem jMenuItemDangXuat;
    private javax.swing.JMenuItem jMenuItemDoiMK;
    private javax.swing.JMenuItem jMenuItemGiamGia;
    private javax.swing.JMenuItem jMenuItemGioiThieu;
    private javax.swing.JMenuItem jMenuItemHuongDan;
    private javax.swing.JMenuItem jMenuItemKetThuc;
    private javax.swing.JMenuItem jMenuItemKhachHang;
    private javax.swing.JMenuItem jMenuItemNhaCungCap;
    private javax.swing.JMenuItem jMenuItemPhieuNhap;
    private javax.swing.JMenuItem jMenuItemPhieuXuat;
    private javax.swing.JMenuItem jMenuItemQLNhanVien;
    private javax.swing.JMenuItem jMenuItemQLNongSan;
    private javax.swing.JMenu jMenuNgonNgu;
    private javax.swing.JMenu jMenuQuanLy;
    private javax.swing.JMenu jMenuTongHop;
    private javax.swing.JMenu jMenuTroGiup;
    private javax.swing.JMenu jMenuUuDai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblDongHo;
    // End of variables declaration//GEN-END:variables
private void init() {
        this.setLocationRelativeTo(null);//đưa cửa sổ ra giữa
        
        initcuasochao();
        initcuasodangnhap();
        innitclock();
    }

    private void initcuasochao() {
        ChaoJ a = new ChaoJ(this, true);
        a.setVisible(true);
    }

    private void initcuasodangnhap() {
        Login b = new Login(this, true);
        b.setVisible(true);
    }

    private void innitclock() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(date);
                lblDongHo.setText(text);
            }
        }).start();
    }
}
